### ISSUE TITLE
Latest version on master is 4.3.0 but trunk shows 4.4.0

### ISSUE THREAD

**Issue by wojteklembryk** [ashfurrow/Nimble-Snapshots#69]
<img width="437" alt="screen shot 2016-11-24 at 16 39 10" src="https://cloud.githubusercontent.com/assets/3175836/20604056/be4b5ae2-b264-11e6-9ed1-b8166b26470a.png">

<img width="909" alt="screen shot 2016-11-24 at 16 38 55" src="https://cloud.githubusercontent.com/assets/3175836/20604061/c2f30eb4-b264-11e6-8212-cb6b109cff8e.png">

**Comment by ashfurrow** [comment]
Hmm, interesting. Is this causing any problems, beyond the inconsistency?

**Comment by wojteklembryk** [comment]
@ashfurrow nope, I just use strict version number in my `Podfile` and it works fine. I can be confusing for new users especially that cocoapods website showing wrong version number.

<img width="538" alt="screen shot 2016-11-24 at 17 45 54" src="https://cloud.githubusercontent.com/assets/3175836/20605936/294c45e6-b26e-11e6-9ba3-043c74c32817.png">

**Comment by ashfurrow** [comment]
Cool, I took a look at my local git directory and I just forgot to push up the change 🙈 Should be fixed now, thanks for letting me know 👍

**Comment by wojteklembryk** [comment]
@ashfurrow unfortunately, I still see ten problem after updating pods repo but I can be on my side. Thanks for quick help and work on this lib :beer:

**Comment by ashfurrow** [comment]
What I mean is, I had forgotten to push the updated 4.4.0 podspec to this repo, which has been updated now ( https://github.com/ashfurrow/Nimble-Snapshots/blob/master/Nimble-Snapshots.podspec#L3 ). Does that make sense?

**Comment by wojteklembryk** [comment]
Nope, it's all fine with podspec but there is no tag/release for version `4.4.0` 
https://github.com/ashfurrow/Nimble-Snapshots/tags 

Thats why I'm getting following error:
<img width="983" alt="screen shot 2016-11-24 at 18 11 15" src="https://cloud.githubusercontent.com/assets/3175836/20606487/8c3f32be-b271-11e6-89f7-98d042962524.png">

**Comment by ashfurrow** [comment]
Oops, sorry! Should be fixed, can you confirm?

**Comment by wojteklembryk** [comment]
Works fine now 🎉 Thank you for help 👍
